### PR TITLE
🚀 release: v0.1.0

### PR DESCRIPTION
**Pull request by warengonzaga**
Hey there @denzdelvillar @jofftiquez, moving forward, we will use this branch for an upcoming update to the project (nightly). For existing issues, let's push them directly to the `main` branch.

### CODE REVIEW

**Comment by warengonzaga** [comment]
The social preview will look like this for Facebook.

image

cc: @denzdelvillar @jofftiquez

**Comment by jofftiquez** [comment]
@warengonzaga kindly use this one. Thanks

og-banner

**Comment by jofftiquez** [comment]
> Hey there @denzdelvillar @jofftiquez, moving forward, we will use this branch for an upcoming update to the project (nightly). For existing issues, let's push them directly to the `main` branch.

For a better management of branches, may I suggest that we stick to trunk-based development? Which will let us have just the `main` branch and just preview links for every PRs. That way we could avoid potential mismatching of `main` and `dev` branches for large PRs.

**Comment by warengonzaga** [comment]
> > Hey there @denzdelvillar @jofftiquez, moving forward, we will use this branch for an upcoming update to the project (nightly). For existing issues, let's push them directly to the `main` branch.
> 
> For a better management of branches, may I suggest that we stick to trunk-based development? Which will let us have just the `main` branch and just preview links for every PRs. That way we could avoid potential mismatching of `main` and `dev` branches for large PRs.

Any reference for trunk-based development? Would love to take a look.

**Comment by warengonzaga** [comment]
> @warengonzaga kindly use this one. Thanks
> 
> og-banner

Thanks, however, I can see a little difference in the color.
image

I get the resolution from the GitHub Social Preview maybe we should follow it but zoom out the actual preview? @jofftiquez

**Comment by jofftiquez** [comment]
> Any reference for trunk-based development? Would love to take a look.

@warengonzaga 

- https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development
- https://www.linkedin.com/pulse/gitflow-vs-trunk-based-development-finding-right-balance-markham/

**Comment by jofftiquez** [comment]
> I get the resolution from the GitHub Social Preview maybe we should follow it but zoom out the actual preview? @jofftiquez

It's okay as long as we follow the dimension `1:1` @warengonzaga

**Comment by warengonzaga** [comment]
> > Any reference for trunk-based development? Would love to take a look.
> 
> @warengonzaga
> 
> * https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development
> * https://www.linkedin.com/pulse/gitflow-vs-trunk-based-development-finding-right-balance-markham/

I have a quick skim to this, basically this is alternative to gitflow, alright we can do this, actually I realized I'm doing this to some of my projects where I can just merge them to main branch just add checkers/linters or CI so that it will not break the main branch.

**Comment by warengonzaga** [comment]
> > I get the resolution from the GitHub Social Preview maybe we should follow it but zoom out the actual preview? @jofftiquez
> 
> It's okay as long as we follow the dimension `1:1` @warengonzaga

I see, let me recreate this later this after noon.

**Comment by jofftiquez** [comment]
> I have a quick skim to this, basically this is alternative to gitflow, alright we can do this, actually I realized I'm doing this to some of my projects where I can just merge them to main branch just add checkers/linters or CI so that it will not break the main branch.

Yes, as long as the CI and linters are set properly, it is best to use trunk-based development. This is what I want to set for all of our repos here in OSSPH. Kindly review as well so we can implement.

**Comment by denzdelvillar** [comment]
Let's move forward with trunk-based dev. Then need to setup CI and auto-formatting. Let's also urge contributors to make relatively small pull requests

**Review by denzdelvillar — APPROVED** [review]
Thanks for this!

**Pull request merged**
