### PR TITLE
Put the saved image button to the layout and made some changes to the style of the homepage

### PR DESCRIPTION
**Pull request by Kuroe27**
I have successfully added the saved image to the layout and have addressed some bugs.

### CODE REVIEW

**Comment by denzdelvillar** [comment]
Hello, thanks for this. Can you help me settle merge conflicts with the latest `main`? Thanks 😅

**Comment by Kuroe27** [comment]
> Hello, thanks for this. Can you help me settle merge conflicts with the latest `main`? Thanks 😅

Certainly, I would be glad to assist you! Although I am still new to using Git, resolving merge conflicts can be a bit challenging.

**Comment by Kuroe27** [comment]
Hello, I have already merged it into the latest main.

**Comment by Kuroe27** [comment]
> 
Hi, I also added changes to the homepage

**Comment by jofftiquez** [comment]
@Kuroe27 any reason for closing the PR? Thanks

**Comment by Kuroe27** [comment]
Hello, I have decided to close this pull request as the project has been updated and my PR has fallen behind. Thank you for your time and effort, and please let me know if there is anything I can do to assist in the future.

**Comment by jofftiquez** [comment]
> Hello, I have decided to close this pull request as the project has been updated and my PR has fallen behind. Thank you for your time and effort, and please let me know if there is anything I can do to assist in the future.

Got it @Kuroe27 thanks as well. Feel free to open a new PR anytime

**Pull request closed without merging**
