### PR TITLE
📜docs: add license

### PR DESCRIPTION
**Pull request by warengonzaga**
Add GPL-3.0 license for the project.

### CODE REVIEW

**Comment by warengonzaga** [comment]
Kindly review @jofftiquez @denzdelvillar thanks!

**Review by jofftiquez — APPROVED** [review]
Looks good

**Comment by jofftiquez** [comment]
Altho, isn't MIT a better choice for the license? @warengonzaga 

CC: @denzdelvillar

**Comment by warengonzaga** [comment]
I would suggest GPL as it is a tool/web app and software that is being used by ppl, using an MIT license unless this is some kind of library or framework.

If it is something ppl can use, GPL is best in my opinion.

**Comment by jofftiquez** [comment]
> I would suggest GPL as it is a tool/web app and software that is being used by ppl, using an MIT license unless this is some kind of library or framework.
> 
> If it is something ppl can use, GPL is best in my opinion.
> 
> in addition, it protects the project @jofftiquez, if they copy it they have to open-source their modified version.

Got it, noted @warengonzaga

**Comment by jofftiquez** [comment]
@denzdelvillar this is for your review and approval thanks

**Pull request merged**
